name: Tag PRs with merge conflicts

on:
  # So that PRs touching the same files as the push are updated
  push:
    branches-ignore:
      - main
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: conflicts
          removeOnDirtyLabel: conflicts
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "⚠️ This PR has conflicts. Please, solve them."
          commentOnClean: "✅ The conflict have been solved! Ready to review."
